src/family_tree/home/urls.py
from . import views
from django.urls import path

app_name = 'home'

urlpatterns = [path('', views.index, name='index')]

src/family_tree/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView

from . import views

app_name = 'main'

urlpatterns = [
    path("graphql", csrf_exempt(GraphQLView.as_view(graphiql=settings.DEBUG))),
    path('settings', views.settingsPanel, name='settingsPanel'),
    path('undo/<int:file_id>', views.undo_do, name='undo_do'),
    path('undo', views.undo_choose, name='undo_choose'),
    path('tos', views.tos, name='tos'),
    path('test', views.test, name='test'),
    path('changes', views.changes, name='changes'),
    path('api/<str:names_str>', views.searchByName, name='searchByName'),
    path('delete_my_account', views.delete_user, name='delete_user'),
    path('<int:orig_id>/<int:person_id>/save/', views.save, name='save'),
    path('edit/<int:person_id>/<int:orig_id>', views.edit, name='edit'),
    path('<int:person_id>', views.person_tree, name='person_tree'),
    path('<int:from_id>/<int:to_id>', views.tree_from_to, name='tree_from_to'),
    path('navigation', views.navigation, name='navigation'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/family_tree/home/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from main.models import Person


class Bookmark(models.Model):
    person = models.OneToOneField(Person,
                                  on_delete=models.CASCADE,
                                  verbose_name=_("Person"))
    color = models.CharField(max_length=6,
                             null=True,
                             blank=True,
                             default=None,
                             verbose_name=_("Color"))
    font_color = models.CharField(max_length=6,
                                  null=True,
                                  blank=True,
                                  default=None,
                                  verbose_name=_("Font Color"))
    font_size = models.PositiveIntegerField(null=True,
                                            blank=True,
                                            default=None,
                                            verbose_name=_("Font Size"))
    label = models.CharField(max_length=200,
                             null=True,
                             blank=True,
                             verbose_name=_("Label"))

    def as_node(self, **args):
        value = self.person.as_node(**args)
        if "title" in value:
            del value["title"]  # remove tooltip (no need)
        value["label"] = f"*{value['label']}*"
        if len(self.person.designation) > 0:
            value["label"] += f"\n({self.person.designation})"

        if self.label is not None and len(self.label) > 0:
            value["label"] = self.label
        if self.color is not None and len(self.color) > 0:
            value["color"] = self.color

        value["font"] = dict()
        value["font"]["multi"] = "markdown"
        if self.font_size is not None:
            value["font"]["size"] = self.font_size
        if self.font_color is not None and len(self.font_color) > 0:
            value["font"]["color"] = self.font_color
        return value

    class Meta:
        ordering = ["person__pk"]

    def __str__(self):
        return self.person.__str__()

src/family_tree/main/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django_registration.forms import (RegistrationFormTermsOfService,
                                       RegistrationFormUniqueEmail)
from main.models import Person, User


class UserForm(RegistrationFormUniqueEmail, RegistrationFormTermsOfService):

    class Meta(RegistrationFormUniqueEmail.Meta):
        model = User
        fields = [
            'username', 'email', 'first_name', 'last_name', 'birth_date',
            'father_name', 'grandfather_name', 'birth_place'
        ]
        widgets = {
            'birth_date': forms.TextInput(attrs={'autocomplete': 'off'})
        }


class SettingsForm(forms.ModelForm):

    class Meta:
        model = User
        fields = [
            'first_name',
            'father_name',
            'grandfather_name',
            'last_name',
            'birth_date',
            'birth_place',
        ]


class PersonForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["designation"].widget.attrs.update({"rows": "3"})
        self.fields["history"].widget.attrs.update({"rows": "3"})
        self.fields["reference"].widget.attrs.update({"rows": "3"})

    children = forms.CharField(label=_("Children"), max_length=1000, required=False)

    class Meta:
        model = Person
        fields = [
            'name',
            'designation',
            'history',
            'reference',
        ]

src/family_tree/home/views.py
from django.shortcuts import render
from home.home_tree_generator import get_tree


def index(req):
    return render(req, 'main/home.html', get_tree())

src/family_tree/main/views.py
import json
import logging
import pathlib
import subprocess

from django.conf import settings
from django.core.exceptions import SuspiciousOperation
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from home.home_tree_generator import generate_home_tree
from home.models import Bookmark
from main.forms import PersonForm, SettingsForm
from main.management.commands.create_db_backup import list_backups
from main.models import Person
from main.session_configs import configs

PROJECT_DIR = str(settings.PROJECT_DIR.absolute())


def person_tree(req, person_id):
    person = get_object_or_404(Person, pk=person_id)
    grandfather = person.get_grandfather()
    levels = []
    if grandfather is not None:
        levels.append([grandfather])
    if person.parent is not None:
        levels.append([person.parent])
    levels.append([person])
    levels.extend(person.expand(depth=2)[1:])
    all_persons = [
        person for level in levels for person in level
        if person.is_visible_to(req.user)
    ]
    data = [p.as_node(req.user) for p in all_persons]
    links = [{
        "id": p.pk,
        "from": p.parent.pk,
        "to": p.pk,
    } for p in all_persons[1:]]
    return render(
        req, 'main/tree.html', {
            "data": json.dumps(data),
            "links": json.dumps(links),
            "main_id": person_id,
            "animation_duration": 500,
        })


def navigation(req):
    return render(req, 'main/tree_navigation.html')


def tree_from_to(req, from_id, to_id):
    matches = []

    for pk in [from_id, to_id]:
        matches.append(Person.objects.filter(pk=pk))
        if not matches[-1].exists():
            return render(req, 'main/tree_navigation.html',
                          {"error": _("Requested person does not exist")})
    from_person = matches[0].first()
    to_person = matches[1].first()
    matches = Person.objects.filter(pk=to_id)
    if not matches.exists():
        return render(req, 'main/tree_navigation.html',
                      {"error": _("Requested person does not exist")})
    to_person = get_object_or_404(Person, pk=to_id)
    levels = []
    if not from_person.is_visible_to(req.user):
        return render(req, 'main/tree_navigation.html',
                      {"error": _("Requested person does not exist")})
    person = to_person
    while person != from_person:
        if not person.is_visible_to(req.user):
            return render(req, 'main/tree_navigation.html',
                          {"error": _("Requested person does not exist")})
        if person.parent is None and person != from_person:
            return render(
                req, 'main/tree_navigation.html',
                {"error": _("Could not find a route from ancestor to child")})
        levels.extend([[person for person in person.parent.children.all()]])
        person = person.parent

    levels.append([from_person])
    all_persons = [
        person for level in levels[::-1] for person in level
        if person.is_visible_to(req.user)
    ]
    data = [p.as_node(req.user) for p in all_persons]
    links = [{
        "id": p.pk,
        "from": p.parent.pk,
        "to": p.pk,
    } for p in all_persons[1:]]
    return render(
        req, 'main/tree.html', {
            "data": json.dumps(data),
            "links": json.dumps(links),
            "main_id": to_person.pk,
            "animation_duration": 5000,
        })


def edit(req, person_id, orig_id):
    person = get_object_or_404(Person, pk=person_id)
    children = ''
    for child in person.children.all():
        if req.user.is_staff or req.user in child.editors.all():
            children += child.name + ','
    init_data = person.__dict__
    init_data["children"] = children[0:-1]
    form = PersonForm(initial=init_data)
    context = {
        'person': person,
        'orig_id': orig_id,
        'form': form,
    }
    return render(req, 'main/edit.html', context)


def save(req, orig_id, person_id):
    person = get_object_or_404(Person, pk=person_id)

    person_children = []
    for child in person.children.all():
        person_children.append(child.name)

    if req.user.is_authenticated:
        for child in req.POST['children'].split(','):
            if not child in person_children and child != '':
                new_child = Person(name=child, parent=person)

                if req.user.is_staff:
                    new_child.access = 'public'
                else:
                    new_child.access = 'private'
                new_child.save()
                new_child.editors.add(req.user)

        for child in person.children.all():
            if child.name in req.POST['children'].split(',') and not (
                    req.user in child.editors.all()):
                child.editors.add(req.user)
                child.save()

    if req.user.is_staff or req.user in person.editors.all():
        person.name = req.POST['name']
        person.designation = req.POST['designation']
        person.history = req.POST['history']

    person.save()

    return HttpResponseRedirect(reverse('main:person_tree', args=(orig_id, )))


def searchByName(req, names_str):
    start = names_str.split(' ')[0]

    parents = []
    ids = []
    for p in Person.objects.filter(name__startswith=start):
        if req.user in p.editors.all(
        ) or p.access == "public" or req.user.is_staff:
            if names_str == str(p)[0:len(names_str)]:
                parents.append(str(p))
                ids.append(p.id)
                if len(parents) > 5:
                    break

    return JsonResponse({'parents': parents, 'ids': ids})


def undo_choose(req):
    files_str = []
    file_names = []
    files = list_backups()
    for file in files:
        year = file.name[-22:-18]
        month = file.name[-18:-16]
        day = file.name[-16:-14]
        hour = file.name[-14:-12]
        minutes = file.name[-12:-10]
        seconds = file.name[-10:-8]
        file_names.append(file.name)
        files_str.append(f"{year}/{month}/{day} - {hour}:{minutes}:{seconds}")
    return render(req, 'main/undo_choose.html', {
        'files_str': files_str,
        'file_names': file_names
    })


def undo_do(req, file_id):
    if req.user.is_staff:
        files = list_backups()
        chosen_file = files[file_id]
        current_db_path_rel = pathlib.Path(
            settings.DATABASES['default']['NAME'])
        root_dir = pathlib.Path(settings.BASE_DIR).parent
        current_db_path = root_dir / current_db_path_rel
        subprocess.call(f"cp {chosen_file} {current_db_path}", shell=True)
        generate_home_tree()
    return HttpResponseRedirect('/')


def tos(req):
    return render(req, 'main/tos.html')


def test(req):
    logging.info("Hello")
    return render(req, 'main/test.html')


def settingsPanel(req):
    if req.user.is_authenticated:
        if req.method == 'POST':
            form = SettingsForm(req.POST)
            if form.is_valid():
                req.user.first_name = req.POST['first_name']
                req.user.father_name = req.POST['father_name']
                req.user.grandfather_name = req.POST['grandfather_name']
                req.user.last_name = req.POST['last_name']
                req.user.birth_date = req.POST['birth_date']
                req.user.birth_place = req.POST['birth_place']
                req.user.save()

                return HttpResponseRedirect('/')

        else:
            form = SettingsForm(instance=req.user)

        return render(req, 'main/settings.html', {'form': form})

    else:

        return HttpResponse(_("You are not logged in!"))


def delete_user(req):
    if req.user.is_authenticated:
        req.user.delete()
    return HttpResponseRedirect('/')


def changes(req):
    changes = [
        person for person in Person.objects.all() if person.access == 'private'
    ]
    return render(req, 'main/changes.html', {'changes': changes})

src/family_tree/main/templates/main/base.html
{% load static %}
{% load read_settings %}
{% load i18n %}
{% load pwa %}

<html lang="{{language_code}}">

<head>
    <script>
        // context variable used to pass template context to javascript files
        const context = {
            user: { is_authenticated: '{{user.is_authenticated}}' == 'True' },
            toolsDisplay: '{{request.session.tools_display}}',
            showToolsText: '{% translate "Show Tools" %}',
            hideToolsText: '{% translate "Hide Tools" %}',
            urls: {
                main: {
                    searchByName: "{% url 'main:searchByName' 1 %}".slice(0, -2),
                    personTree: "{% url 'main:person_tree' 1 %}".slice(0, -2),
                    edit: "{% url 'main:edit' 1 2 %}".slice(0, -4),
                    treeFromTo: "{% url 'main:tree_from_to' 1 2 %}".slice(0, -4),
                },
                home: {
                    index: "{% url 'home:index' %}",
                }
            }
        }
    </script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% progressive_web_app_meta %}
    <title>{% read_settings "SITE_NAME" %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'favicon.png' %}">
    <link href="{% static "css/base.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/thirdparty/pikaday.css" %}" rel="stylesheet" type="text/css">
    <script src="{% static "js/thirdparty/moment.js" %}"></script>
    <script src="{% static "js/thirdparty/pikaday.js" %}"></script>
    <link href="{% static "css/edit_page.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/accounts.css" %}" rel="stylesheet" type="text/css">
    <script src="https://kit.fontawesome.com/8d80fe0cea.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "css/thirdparty/choices.css" %}">
    <script src="{% static "js/thirdparty/choices.min.js" %}"></script>
    <script src="{% static "js/base.js" %}"></script>
    {% block header %}{% endblock %}
</head>

<body class="{{ text_direction }}" dir="{{ text_direction }}">

    <div class="flex-container">
        {% include "main/navbar.html" %}
        <div class="content">
            {% block content %}{% endblock %}
        </div>
    </div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock %}
</body>

</html>

src/family_tree/main/templates/main/changes.html
{% extends 'main/base.html' %}
{% load i18n %}
{% load static %}

{% block header %}
<script type="text/javascript" src="{% static "js/thirdparty/apollo-client.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/thirdparty/tablefilter/tablefilter.js" %}"></script>
<link rel="stylesheet" href="{% static "css/changes.css" %}">
{% endblock %}

{% block content %}
<script type="module" src="{% static "js/changes.js" %}"></script>
{% if user.is_staff %}
<br>
<br>
<br>

<div class="container">
    <h4> {% translate "Unpublished Additions" %} </h4>
    <br><br>

    <div class="table-responsive-lg">
        <table id="changesTable" class="table table-striped">
            <thead>
                <tr>
                    <th scope="col"> {% translate "User" %} </th>
                    <th scope="col"> {% translate "User Email" %} </th>
                    <th scope="col"> {% translate "User Type" %} </th>
                    <th scope="col"> {% translate "Added Person" %}</th>
                    <th scope="col"> {% translate "Creation Time" %} </th>
                    <th scope="col"> {% translate "Last Modification" %} </th>
                    <th scope="col"> {% translate "Actions" %} </th>
                </tr>
            </thead>
            <tbody>

                {% for person in changes %}
                {% for editor in person.editors.all %}
                <tr>
                    <td> {{editor}} </td>
                    <td> {{editor.email}} </td>
                    <td> {{editor.user_type}} </td>
                    <td> {{person}} </td>
                    <td> {{person.creation_time}} </td>
                    <td> {{person.last_modified}} </td>
                    <td>
                        <button class="btn btn-success btn-lg actionBtn" type="button" data-person-id="{{person.id}}"><i
                                class="fas fa-check"></i></button>
                        <button class="btn btn-primary btn-lg actionBtn" type="button"
                            onclick="window.location = '{% url 'main:person_tree' person.id %}' ">
                            {% if text_direction == "ltr" %}
                            <i class="fas fa-arrow-right"></i>
                            {% else %}
                            <i class="fas fa-arrow-left"></i>
                            {% endif %}
                        </button>
                    </td>
                </tr>
                {% endfor %}
                {% endfor %}

            </tbody>
        </table>
    </div>
    <br><br>
    <button id="cancelBtn" onclick="window.history.back()" class="btn btn-danger btn-lg" type="button"> {% translate "Cancel" %} </button>

</div>
{% endif %}

<script>
    var tf = new TableFilter(document.getElementById('changesTable'), {
        base_path: "{% static 'js/thirdparty/tablefilter' %}",
        themes: [{
            name: 'transparent'
        }],
        alternate_rows: true,
        btn_reset: true,
        rows_counter: true,
        loader: true,
        col_2: 'select',
        on_filters_loaded: function(tf){
        tf.setFilterValue(2, 'Staff');
        tf.filter();
      },
        no_results_message: true,
    });
    tf.init();
</script>

{% endblock %}

src/family_tree/main/templates/main/confirmation_modal.html
{% load i18n %}

<style>
    .mask {
        background: rgba(0, 0, 0, 0.5);
        position: fixed;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
    }

    .modal-dialog-custom {
        margin-top: 30vh;
    }

    .custom-close{
        background-color: transparent;
        border: none;
        font-size: 1.5em;
        color: rgb(125, 125, 125);
    }
</style>

<div id="{{namespace}}Modal" class="modal">
    <div class="mask"></div>
    <div class="modal-dialog modal-dialog-custom">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"> {{title}} </h5>
                <button type="button" class="custom-close" onclick="hide{{namespace}}Modal()">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>
                    {{ body }}
                </p>
            </div>
            <div class="modal-footer">
                <button id="{{namespace}}Button" class="btn btn-danger" type="button""> {% translate "Confirm" %} </button>
            </div>
        </div>
    </div>
</div>

<script>
    function hide{{namespace}}Modal() {
        const modal = document.getElementById("{{namespace}}Modal");
        modal.style.display = "none";
    }
    // When the user clicks anywhere outside of the modal, close it
    window.onclick = (event)=> {
        const mask = document.getElementsByClassName("mask")[0];
    if (event.target == mask) {
        const modal = document.getElementById("{{namespace}}Modal");
        modal.style.display = "none";
        }
    }
</script>

src/family_tree/main/templates/main/edit.html
{% extends 'main/base.html' %}
{% load i18n %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static "css/edit.css" %}">
{% endblock %}


{% block content %}
{% if user.is_authenticated %}


<div class="container custom-section">
    <div class="row justify-content-center">
        <div class="col-sm-7">
            <form action="{% url 'main:save' orig_id person.id %}" method="post">
                {% csrf_token %}
                {{ form }}
                <div class="edit-buttons-container">
                    <input type="submit" value='{% translate "Save" %}' class="btn btn-primary btn-lg editFormButtons">
                    <button class="btn btn-danger btn-lg editFormButtons" type="button"
                        onclick="window.location = '{% url 'main:person_tree' orig_id%}'"> {% translate "Cancel" %}
                    </button>
                </div>
            </form>
        </div>
    </div>
    <br>
    <br>
    <br>

</div>


{% endif %}


<script>

    window.addEventListener("load", () => {
        const childrenInput = document.getElementById("{{form.children.id_for_label}}");
        const choices1 = new Choices(childrenInput, {
            delimiter: ',',
            editItems: true,
            removeItems: false,
            addItemText: (value) => {
                return "{% translate 'Press Enter to add a child' %}";
            },
        });

        {% if person.access == "public" and not user.is_staff %}
        const disabledFields = ["name", "reference", "history", "designation"]
        disabledFields.forEach((field_name) => {
            const field = document.getElementById(`id_${field_name}`);
            field.disabled = true;
            field.style.background = "#e9ecef";
        })
        {% endif %}

    });
</script>
{% endblock %}

src/family_tree/main/templates/main/navbar.html
{% load static %}
{% load i18n %}

<link href="{% static "css/navbar.css" %}" rel="stylesheet" type="text/css">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav {% if text_direction == 'rtl' %} ml-auto {% else %} mr-auto {% endif %} no-padding">
            <li class="nav-item active nav-link-custom nav-item-margin">
                <a class="nav-link" href={% url 'home:index' %}> {% translate "Home" %} </a>
            </li>
            <li class="nav-item active nav-link-custom nav-item-margin">
                <a class="nav-link" href={% url 'main:navigation' %}> {% translate "From - To" %} </a>
            </li>
            <li class="nav-item active nav-link-custom nav-item-margin">
                <a class="nav-link" href="/help"> {% translate "Help" %}</a>
            </li>
            <li class="nav-item active nav-link-custom nav-item-margin">
                <a class="nav-link" href="/about"> {% translate "About" %}</a>
            </li>
        </ul>
        {% if not user.is_authenticated %}
        <button onclick="window.location = '{% url 'login' %}?next={{ request.path }}' " type="button"
            class="btn btn-primary nav-item-margin"> {% translate "Login" %} </button>
        {% endif %}
        {% if user.is_authenticated %}
        <ul class="navbar-nav no-padding">
            <li class="nav-item active dropdown">
                <a class="dropdown-toggle btn btn-danger nav-item-margin expand-on-small" href="" role="button"
                    data-toggle="dropdown" aria-expanded="false">
                    {{ user }} <i class="fas fa-wrench"></i>
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'main:settingsPanel' %}"> {% translate "Account" %} </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}?next={% url 'home:index' %}"> {% translate "Logout" %}
                    </a>
                </div>
            </li>
        </ul>
        {% endif %}
        {% if user.is_staff %}
        <button onclick="window.location = '{% url 'main:undo_choose' %}' " type="button"
            class="btn btn-danger nav-item-margin expand-on-small">
            <i class="fas fa-history extra-padding"></i>
        </button>
        <button onclick="window.location = '{% url 'main:changes' %}' " type="button"
            class="btn btn-danger nav-item-margin expand-on-small">
            <i class="fas fa-bell extra-padding"></i>
            {% if notifications > 0 %}
                <span class="badge badge-{{text_direction}}">{{notifications}}</span>
            {% endif %}
        </button>
        {% endif %}
        <div class="btn-group search-container nav-item-margin expand-on-small search-box">
            <input oninput="search()" id="searchTxt" class="form-control" placeholder="{% translate 'Search by name' %}"
                aria-label="Search">
            <div id="searchBox" class="dropdown-menu">
                <div class="list-group" id="searchItems"></div>
            </div>
        </div>
    </div>
</nav>

src/family_tree/main/templates/main/settings.html
{% extends 'main/base.html' %}
{% load i18n %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static "css/settings.css" %}">
{% endblock %}


{% block content %}
{% if user.is_authenticated %}
<br><br><br><br>
<div class="container">
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <br><br>
    <button type="submit" class="btn btn-success btn-lg"> {% translate "Save" %} </button>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <button class="btn btn-danger btn-lg" type="button" onclick="window.location = '{% url 'home:index' %}' ">
      {% translate "Cancel" %} </button>

    <br><br><br><br>
    <hr>
    <p> {% translate "Do you want to close your account and delete permanently?" %} </p>
    <button id="Btn-del" class="btn btn-danger" type="button"> {% translate "Delete Account" %} </button>
  </form>
</div>
<br>
<br>
<br>

{% include "main/confirmation_modal.html" with namespace="confirm" title=_("Confirm Deletion") body=_("Deleting your account will delete all your data including persons you added to the family tree which have not been published yet") %}

<script>
  var btn_del = document.getElementById("Btn-del");
  btn_del.onclick = function () {
    const modal = document.getElementById("confirmModal");
    modal.style.display = "block";
    const confirmButton = document.getElementById("confirmButton");
    confirmButton.onclick = () => {
      window.location = '{% url 'main:delete_user' %}';
    }
  }
</script>

<script>

  //moment.locale('ar');
  var picker = new Pikaday({

    field: document.getElementById('{{form.birth_date.id_for_label}}'),
    firstDay: 1,
    minDate: new Date(1900, 1, 1),
    maxDate: new Date({% now "Y" %}, 12, 31),
    yearRange: [1900, {% now "Y" %}],
  format: 'YYYY-MM-DD',
    isRTL: true,
      i18n: {
    previousMonth: 'الشهر السابق',
      nextMonth     : 'الشهر التالي',
        months        : ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'],
          weekdays      : ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'],
            weekdaysShort : ['حد', 'ثن', 'ثل', 'ربع', 'خمس', 'جمع', 'سبت']
  },
  onSelect: function() {
  }
             });

</script>
{% endif %}
{% endblock %}

src/family_tree/main/templates/main/test.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container custom-section">
<h1> Hello </h1>

{{site}}
{{current_domain}}
</div>
{% endblock %}

src/family_tree/main/templates/main/undo_choose.html
{% extends 'main/base.html' %}
{% load i18n %}

{% block header %}
<style>
    .container {
        margin: 100px auto;
        width: 90%;
        max-width: 500px;
    }

    #cancelBtn {
        width: 7em;
    }
</style>
{% endblock %}


{% block content %}
{% if user.is_staff %}

<div class="container">
    <h4> {% translate "Pick a restore point of the database:" %}</h4>
    <br><br>
    <div class="list-group">

        {% for file in files_str %}
        <a href="{% url 'main:undo_do' forloop.counter0 %}" class="list-group-item list-group-item-action"> {{file}}
        </a>
        {% endfor %}

    </div>
    <br><br>
    <button id="cancelBtn" onclick="window.history.back()" class="btn btn-danger btn-lg" type="button">
        {% translate "Cancel" %} </button>
</div>

{% endif %}
{% endblock %}