src/family_tree/home/urls.py
from . import views
from django.urls import path

app_name = 'home'

urlpatterns = [path('', views.index, name='index')]

src/family_tree/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView

from . import views

app_name = 'main'

urlpatterns = [
    path("graphql", csrf_exempt(GraphQLView.as_view(graphiql=settings.DEBUG))),
    path('settings', views.settingsPanel, name='settingsPanel'),
    path('undo/<int:file_id>', views.undo_do, name='undo_do'),
    path('undo', views.undo_choose, name='undo_choose'),
    path('tos', views.tos, name='tos'),
    path('test', views.test, name='test'),
    path('changes', views.changes, name='changes'),
    path('api/<str:names_str>', views.searchByName, name='searchByName'),
    path('delete_my_account', views.delete_user, name='delete_user'),
    path('<int:orig_id>/<int:person_id>/save/', views.save, name='save'),
    path('edit/<int:person_id>/<int:orig_id>', views.edit, name='edit'),
    path('<int:person_id>', views.person_tree, name='person_tree'),
    path('<int:from_id>/<int:to_id>', views.tree_from_to, name='tree_from_to'),
    path('navigation', views.navigation, name='navigation'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/family_tree/main/models.py
from collections import deque

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.validators import EmailValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

User = settings.AUTH_USER_MODEL

N_COLORS = 11  # number of colors in the tree color palette/theme (check main/static/tree_color_palettes.js)


class Person(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("Name"))
    parent = models.ForeignKey('self',
                               on_delete=models.CASCADE,
                               null=True,
                               blank=True,
                               related_name="children",
                               verbose_name=_("Parent"))
    reference = models.TextField(
        max_length=1000,
        blank=True,
        verbose_name=_("Reference of authentication (optional)"))
    designation = models.TextField(max_length=500,
                                   blank=True,
                                   verbose_name=_("Designation (optional)"))
    history = models.TextField(
        max_length=2000,
        blank=True,
        verbose_name=_("Historical Background (optional)"))
    editors = models.ManyToManyField(User, verbose_name=_("Editor"))
    access_choices = [('public', 'public'), ('private', 'private')]
    access = models.CharField(max_length=200,
                              choices=access_choices,
                              default='public')
    creation_time = models.DateTimeField(auto_now_add=True,
                                         verbose_name=_("Date of creation"))
    last_modified = models.DateTimeField(
        auto_now=True, verbose_name=_("Date of last modification"))

    def is_visible_to(self, user: User):
        """
        Checks whether the given user has view permission
        """
        if self.access == "public":
            return True
        if user.is_staff:
            return True
        return user in self.editors.all()

    def is_editable_by(self, user: User):
        """
        Checks whether the given user has edit permission
        """
        if user.is_staff:
            return True
        if self.is_public():
            return False
        editors = self.editors.all()
        if user in editors and len(editors) == 1:
            return True
        return False

    def expand(self, depth=5):
        buffer = deque([self])
        #all_persons = []
        levels = []
        while len(buffer) > 0 and depth >= 0:
            depth -= 1
            new_buffer = deque([])
            level = []
            while len(buffer) > 0:
                person = buffer.pop()
                #all_persons.append(person)
                level.append(person)
                new_buffer.extend(list(person.children.all()))
            levels.append(level)
            buffer = new_buffer
        return levels

    def get_grandfather(self):
        if self.parent is None:
            return None
        if self.parent.parent is None:
            return None
        return self.parent.parent

    def _get_father(self, parent, depth):
        try:
            if depth > 1:
                return parent.name + ' ' + self._get_father(
                    parent.parent, depth - 1)
            else:
                return ''
        except:
            return ''

    def __str__(self):
        return self.name + ' ' + self._get_father(self.parent, 6)

    def is_public(self):
        return self.access == "public"

    def is_bookmarked(self):
        return hasattr(self, "bookmark")

    def as_node(self, user: User = None, forced_group=None):
        """
        Returns the vis.js node representation
        """
        opacity = 1.0
        if user is not None and user.is_staff:
            opacity = 1.0 if self.is_public() else 0.3
        if forced_group is None:
            group_code = f"g{(self.parent.pk if self.parent else 0) % N_COLORS}"
        else:
            group_code = f"g{forced_group}"
        title = f"{self.designation}\n{self.history}"
        data = {
            "id": self.pk,
            "label": self.name,
            "group": group_code,
            "opacity": opacity,
        }
        if len(title) > 1:
            data["title"] = title
            data["font"] = {
                "strokeWidth": 5,
            }
        return data

    def find_closest_parent(self, persons):
        """
        Returns closest parent among given persons list, and how far is it 
        """
        parent = self.parent
        length = 1
        while parent is not None:
            if parent in persons:
                return parent, length
            length += 1
            parent = parent.parent
        return None, -1

    def remove_editor(self, user):
        editors = list(self.editors.all())
        if len(editors) == 1 and editors[0].is_staff:
            return
        self.editors.remove(user)
        self.save()


class User(AbstractUser):
    email = models.EmailField(
        null=True,
        blank=True,
        unique=True,
        validators=[EmailValidator(message=_("Enter a valid email address"))])
    birth_date = models.DateField(null=True,
                                  blank=False,
                                  verbose_name=_("Date of birth"))

    first_name = models.CharField(max_length=150,
                                  null=True,
                                  blank=False,
                                  verbose_name=_("First name"))
    father_name = models.CharField(max_length=150,
                                   null=True,
                                   blank=False,
                                   verbose_name=_("Father's name"))
    grandfather_name = models.CharField(max_length=150,
                                        null=True,
                                        blank=False,
                                        verbose_name=_("Grandfather's name"))
    last_name = models.CharField(max_length=150,
                                 null=True,
                                 blank=False,
                                 verbose_name=_("Last name"))

    birth_place = models.CharField(max_length=150,
                                   null=True,
                                   blank=False,
                                   verbose_name=_("Place of birth"))

    @property
    def user_type(self):
        if self.is_superuser:
            return "Staff"
        if self.is_staff:
            return "Staff"
        if self.is_authenticated:
            return "normal"
        return "Anonymous"

src/family_tree/main/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django_registration.forms import (RegistrationFormTermsOfService,
                                       RegistrationFormUniqueEmail)
from main.models import Person, User


class UserForm(RegistrationFormUniqueEmail, RegistrationFormTermsOfService):

    class Meta(RegistrationFormUniqueEmail.Meta):
        model = User
        fields = [
            'username', 'email', 'first_name', 'last_name', 'birth_date',
            'father_name', 'grandfather_name', 'birth_place'
        ]
        widgets = {
            'birth_date': forms.TextInput(attrs={'autocomplete': 'off'})
        }


class SettingsForm(forms.ModelForm):

    class Meta:
        model = User
        fields = [
            'first_name',
            'father_name',
            'grandfather_name',
            'last_name',
            'birth_date',
            'birth_place',
        ]


class PersonForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["designation"].widget.attrs.update({"rows": "3"})
        self.fields["history"].widget.attrs.update({"rows": "3"})
        self.fields["reference"].widget.attrs.update({"rows": "3"})

    children = forms.CharField(label=_("Children"), max_length=1000, required=False)

    class Meta:
        model = Person
        fields = [
            'name',
            'designation',
            'history',
            'reference',
        ]

src/family_tree/main/views.py
import json
import logging
import pathlib
import subprocess

from django.conf import settings
from django.core.exceptions import SuspiciousOperation
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from home.home_tree_generator import generate_home_tree
from home.models import Bookmark
from main.forms import PersonForm, SettingsForm
from main.management.commands.create_db_backup import list_backups
from main.models import Person
from main.session_configs import configs

PROJECT_DIR = str(settings.PROJECT_DIR.absolute())


def person_tree(req, person_id):
    person = get_object_or_404(Person, pk=person_id)
    grandfather = person.get_grandfather()
    levels = []
    if grandfather is not None:
        levels.append([grandfather])
    if person.parent is not None:
        levels.append([person.parent])
    levels.append([person])
    levels.extend(person.expand(depth=2)[1:])
    all_persons = [
        person for level in levels for person in level
        if person.is_visible_to(req.user)
    ]
    data = [p.as_node(req.user) for p in all_persons]
    links = [{
        "id": p.pk,
        "from": p.parent.pk,
        "to": p.pk,
    } for p in all_persons[1:]]
    return render(
        req, 'main/tree.html', {
            "data": json.dumps(data),
            "links": json.dumps(links),
            "main_id": person_id,
            "animation_duration": 500,
        })


def navigation(req):
    return render(req, 'main/tree_navigation.html')


def tree_from_to(req, from_id, to_id):
    matches = []

    for pk in [from_id, to_id]:
        matches.append(Person.objects.filter(pk=pk))
        if not matches[-1].exists():
            return render(req, 'main/tree_navigation.html',
                          {"error": _("Requested person does not exist")})
    from_person = matches[0].first()
    to_person = matches[1].first()
    matches = Person.objects.filter(pk=to_id)
    if not matches.exists():
        return render(req, 'main/tree_navigation.html',
                      {"error": _("Requested person does not exist")})
    to_person = get_object_or_404(Person, pk=to_id)
    levels = []
    if not from_person.is_visible_to(req.user):
        return render(req, 'main/tree_navigation.html',
                      {"error": _("Requested person does not exist")})
    person = to_person
    while person != from_person:
        if not person.is_visible_to(req.user):
            return render(req, 'main/tree_navigation.html',
                          {"error": _("Requested person does not exist")})
        if person.parent is None and person != from_person:
            return render(
                req, 'main/tree_navigation.html',
                {"error": _("Could not find a route from ancestor to child")})
        levels.extend([[person for person in person.parent.children.all()]])
        person = person.parent

    levels.append([from_person])
    all_persons = [
        person for level in levels[::-1] for person in level
        if person.is_visible_to(req.user)
    ]
    data = [p.as_node(req.user) for p in all_persons]
    links = [{
        "id": p.pk,
        "from": p.parent.pk,
        "to": p.pk,
    } for p in all_persons[1:]]
    return render(
        req, 'main/tree.html', {
            "data": json.dumps(data),
            "links": json.dumps(links),
            "main_id": to_person.pk,
            "animation_duration": 5000,
        })


def edit(req, person_id, orig_id):
    person = get_object_or_404(Person, pk=person_id)
    children = ''
    for child in person.children.all():
        if req.user.is_staff or req.user in child.editors.all():
            children += child.name + ','
    init_data = person.__dict__
    init_data["children"] = children[0:-1]
    form = PersonForm(initial=init_data)
    context = {
        'person': person,
        'orig_id': orig_id,
        'form': form,
    }
    return render(req, 'main/edit.html', context)


def save(req, orig_id, person_id):
    person = get_object_or_404(Person, pk=person_id)

    person_children = []
    for child in person.children.all():
        person_children.append(child.name)

    if req.user.is_authenticated:
        for child in req.POST['children'].split(','):
            if not child in person_children and child != '':
                new_child = Person(name=child, parent=person)

                if req.user.is_staff:
                    new_child.access = 'public'
                else:
                    new_child.access = 'private'
                new_child.save()
                new_child.editors.add(req.user)

        for child in person.children.all():
            if child.name in req.POST['children'].split(',') and not (
                    req.user in child.editors.all()):
                child.editors.add(req.user)
                child.save()

    if req.user.is_staff or req.user in person.editors.all():
        person.name = req.POST['name']
        person.designation = req.POST['designation']
        person.history = req.POST['history']

    person.save()

    return HttpResponseRedirect(reverse('main:person_tree', args=(orig_id, )))


def searchByName(req, names_str):
    start = names_str.split(' ')[0]

    parents = []
    ids = []
    for p in Person.objects.filter(name__startswith=start):
        if req.user in p.editors.all(
        ) or p.access == "public" or req.user.is_staff:
            if names_str == str(p)[0:len(names_str)]:
                parents.append(str(p))
                ids.append(p.id)
                if len(parents) > 5:
                    break

    return JsonResponse({'parents': parents, 'ids': ids})


def undo_choose(req):
    files_str = []
    file_names = []
    files = list_backups()
    for file in files:
        year = file.name[-22:-18]
        month = file.name[-18:-16]
        day = file.name[-16:-14]
        hour = file.name[-14:-12]
        minutes = file.name[-12:-10]
        seconds = file.name[-10:-8]
        file_names.append(file.name)
        files_str.append(f"{year}/{month}/{day} - {hour}:{minutes}:{seconds}")
    return render(req, 'main/undo_choose.html', {
        'files_str': files_str,
        'file_names': file_names
    })


def undo_do(req, file_id):
    if req.user.is_staff:
        files = list_backups()
        chosen_file = files[file_id]
        current_db_path_rel = pathlib.Path(
            settings.DATABASES['default']['NAME'])
        root_dir = pathlib.Path(settings.BASE_DIR).parent
        current_db_path = root_dir / current_db_path_rel
        subprocess.call(f"cp {chosen_file} {current_db_path}", shell=True)
        generate_home_tree()
    return HttpResponseRedirect('/')


def tos(req):
    return render(req, 'main/tos.html')


def test(req):
    logging.info("Hello")
    return render(req, 'main/test.html')


def settingsPanel(req):
    if req.user.is_authenticated:
        if req.method == 'POST':
            form = SettingsForm(req.POST)
            if form.is_valid():
                req.user.first_name = req.POST['first_name']
                req.user.father_name = req.POST['father_name']
                req.user.grandfather_name = req.POST['grandfather_name']
                req.user.last_name = req.POST['last_name']
                req.user.birth_date = req.POST['birth_date']
                req.user.birth_place = req.POST['birth_place']
                req.user.save()

                return HttpResponseRedirect('/')

        else:
            form = SettingsForm(instance=req.user)

        return render(req, 'main/settings.html', {'form': form})

    else:

        return HttpResponse(_("You are not logged in!"))


def delete_user(req):
    if req.user.is_authenticated:
        req.user.delete()
    return HttpResponseRedirect('/')


def changes(req):
    changes = [
        person for person in Person.objects.all() if person.access == 'private'
    ]
    return render(req, 'main/changes.html', {'changes': changes})

src/family_tree/main/templates/django_registration/activation_complete.html
{% extends 'main/base.html' %}
{% load i18n %}
{% block content %}
<br>
<br>
<div class="container" style="text-align: center;">
        <span style="font-size: 3em; color: #0eb15a;">
                <i class="fas fa-check-square fa-4x"></i>
        </span>
        <br><br>
        <h1> {% translate "Activation Successful!" %} </h1>
        <hr>
        <br>
        <p>
                {% translate "You can now login with your new account" %}
        </p>
        <br>
        <p>
                {% translate "As a user, you can add new persons to the tree." %}
                {% translate "Your changes will be local and only visible to you." %}<br>
                {% translate "Once a staff member verifies and approves your changes, they will be global and appear to all users." %}
                <br>
                {% translate "Staff members are periodically reviewing and approving changes, but it may take some time." %}<br>
                {% translate "You may also be contacted by the staff reviewing your changes" %}
        </p>
        <button class="btn btn-success btn-lg" onclick="window.location = '{% url 'login'%}' "> {% translate "Login" %}
        </button>
        <br><br>
</div>
{% endblock %}

src/family_tree/main/templates/django_registration/activation_failed.html
{% extends 'main/base.html' %}
{% load i18n %}
{% block content %}
<br>
<br>
<div class="container" style="text-align: center;">
        <span style="font-size: 3em; color: #f02b45;">
                <i class="fas fa-exclamation-triangle fa-4x"></i>
        </span>
        <br><br>

        <h1>
                {% translate "Account Activation Failed!" %}
        </h1>
        <hr>
        <br><br>
        <p>
                {{activation_error.message}}
        </p>

        <button class="btn btn-success btn-lg" onclick="window.location = '{% url 'home:index' %}' ">
                {% translate "Home Page" %}
        </button>
        <br>
</div>
{% endblock %}

src/family_tree/main/templates/django_registration/registration_closed.html
{% extends 'main/base.html' %}
{% load i18n %}
{% block content %}
<br>
<br>
<div class="container" style="text-align: center;">
    <span style="font-size: 3em; color: #f02b45;">
        <i class="fas fa-door-closed fa-4x"></i>
    </span>
    <br><br>
    <h1> {% translate "Registration Closed!" %} </h1>
    <hr>
    <br>
    <p>
        {% translate "We have temporally closed account registration" %}
        <br><br>
    </p>
    <br><br>
    <button class="btn btn-success btn-lg" onclick="window.location = '{% url 'home:index'%}' "> {% translate "Home Page" %} </button>
</div>
{% endblock %}

src/family_tree/main/templates/django_registration/registration_complete.html
{% extends 'main/base.html' %}
{% load i18n %}
{% block content %}
<br>
<br>
<div class="container" style="text-align: center;">
    <span style="font-size: 3em; color: #f02b45;">
        <i class="fas fa-envelope-open-text fa-4x"></i>
    </span>
    <br><br>
    <h1> {% translate "Thanks for Joining!" %} </h1>
    <hr>
    <br>
    <p>
        {% translate "We have sent an email to you" %}
        <br><br>
        {% translate "Please activate your account by clicking on the activation link included in the email" %}
        <br><br>
        {% translate "Note"%}: <br>
        {% translate "please also check your spam/junk folder" %}
    </p>
    <br><br>
    <button class="btn btn-success btn-lg" onclick="window.location = '{% url 'home:index'%}' "> {% translate "Home Page" %} </button>
</div>
{% endblock %}

src/family_tree/main/templates/django_registration/registration_form.html
{% extends 'main/base.html' %}
{% load i18n %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static "css/login.css" %}">
{% endblock %}

{% block content %}
<div class="container custom-section">
    <h5>
        {% translate "Please fill-in below your data (all fields)" %}
    </h5>
    <br>
    <form method="POST">
        {% csrf_token %}

        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="{{form.username.id_for_label}}"> {% translate "Username" %} </label>
                <br>
                {{form.username}}
                {{ form.username.errors }}
                <div id="username_help" style="display: none">
                    {{ form.username.help_text }}
                </div>
            </div>
            <div class="form-group col-md-6 ">
                <label for="{{form.email.id_for_label}}"> {% translate "Email" %} </label>
                <br>
                {{form.email}}
                {{ form.email.errors }}
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6 ">
                <label for="{{form.first_name.id_for_label}}"> {% translate "First Name" %} </label>
                <br>
                {{form.first_name}}
                {{ form.first_name.errors }}
            </div>
            <div class="form-group col-md-6 ">
                <label for="{{form.first_name.id_for_label}}"> {% translate "Father's Name" %} </label>
                <br>
                {{form.father_name}}
                {{ form.father_name.errors }}
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6 ">
                <label for="{{form.first_name.id_for_label}}"> {% translate "Grandfather's Name" %} </label>
                <br>
                {{form.grandfather_name}}
                {{ form.grandfather_name.errors }}
            </div>

            <div class="form-group col-md-6 ">
                <label for="{{form.last_name.id_for_label}}"> {% translate "Family Name" %} </label>
                <br>
                {{form.last_name}}
                {{ form.last_name.errors }}
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6 ">
                <label for="{{form.username.id_for_label}}"> {% translate "Password" %} <button type="button"
                        class="btn btn-link" onclick="
                        toggle_display('pass_help')
                        ">({% translate "?" %})</button> </label>
                <br>
                {{form.password1}}
                {{ form.password1.errors }}
                <div id="pass_help" style="display: none">
                    {{ form.password1.help_text }}
                </div>
            </div>

            <div class="form-group col-md-6 ">
                <label for="{{form.username.id_for_label}}"> {% translate "Confirm Password" %} </label>
                <br>
                {{form.password2}}
                {{ form.password2.errors }}

            </div>

        </div>


        <div class="form-row">
            <div data-locale="ar" class="form-group col-md-6 ">
                <label for="{{form.birth_date.id_for_label}}"> {% translate "Date of Birth" %} </label>
                <br>
                {{form.birth_date}}
                {{ form.birth_date.errors }}

            </div>

            <div class="form-group col-md-6 ">
                <label for="{{form.first_name.id_for_label}}"> {% translate "Place of Birth" %} </label>
                <br>
                {{form.birth_place}}
                {{ form.birth_place.errors }}
            </div>

        </div>



        <div class="form-row">
            <div class="form-group col-md-6">
                {{form.tos}}
                {{ form.tos.errors }}
                <label for="{{form.tos.id_for_label}}"> {% translate "I agree on the" %}
                    <a target="blank" href="{% url 'main:tos' %}">
                        {% translate "terms of use" %}
                    </a> . 
                </label>
            </div>
        </div>

        <br>

        <button type="submit" class="btn btn-success"> {% translate "Create Account" %} </button>

        <br><br>
        <hr>
        {% translate "Already have an account? Go to " %}
        <a href="{% url 'login' %}"><strong> {% translate "Login" %} </strong></a>
        <br>
        <br>
        <br>
    </form>
</div>


<script>
    function toggle_display(id) {
        var x = document.getElementById(id);
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    } 
</script>

<script>
    //moment.locale('ar');
    var picker = new Pikaday({

        field: document.getElementById('{{form.birth_date.id_for_label}}'),
        firstDay: 1,
        minDate: new Date(1900, 1, 1),
        maxDate: new Date({% now "Y" %}, 12, 31),
        yearRange: [1900, {% now "Y" %}],
    format: 'YYYY-MM-DD',
        isRTL: {% if text_direction == rtl %} true {% else %} false {% endif %},
            i18n: {
        previousMonth: "{% translate 'Previous Month' %}",
        nextMonth: "{% translate 'Next Month' %}",
        months: ["{% translate 'January' %}",
                 "{% translate 'February' %}",
                 "{% translate 'March' %}",
                 "{% translate 'April' %}",
                 "{% translate 'May' %}",
                 "{% translate 'June' %}",
                 "{% translate 'July' %}",
                 "{% translate 'August' %}",
                 "{% translate 'September' %}",
                 "{% translate 'October' %}",
                 "{% translate 'November' %}",
                 "{% translate 'December' %}"],
        weekdays: ["{% translate 'Sunday' %}",
                   "{% translate 'Monday' %}" ,
                   "{% translate 'Tuesday' %}",
                   "{% translate 'Wednesday' %}",
                   "{% translate 'Thursday' %}",
                   "{% translate 'Friday' %}",
                   "{% translate 'Saturday' %}"],
        weekdaysShort: ["{% translate 'Sun' %}",
                        "{% translate 'Mon' %}",
                        "{% translate 'Tue' %}",
                        "{% translate 'Wed' %}",
                        "{% translate 'Thu' %}",
                        "{% translate 'Fri' %}",
                        "{% translate 'Sat' %}",]
    },
    onSelect: function() { }
    });
</script>


{% endblock %}